language: java
jdk:
- oraclejdk8
services:
- docker
deploy:
  - provider: releases
    api_key:
      secure: cnm97Hjiemox19I+ZE6VzD3qWYh//IgZQwIq5hyylm2pbr8jY+0Vot1gSVsNZ3ul1d1hVCsDVxuAsGLb8mjNHsOKmwklq6ASQhpfPU5UJG4ygtxiMf6CHxq6H3ypLd4XKvEILrTm/3XXYDXGaXe85f8lnRNL4KUDAHoTOudgLIG+ZnHGgxGyeKz/rvsXRtjFhmhnDn3y0hsZdPX+1cH1cecRU8YguD4aEBsuazvQ2I/eGICLU2D8kByFCTAuWcXVgj/pke8kGZWjb1VLw+SjSK3FtrOvocUPpJsUqFBDNJWrZTsOwxYVCs2dQUUCa1XcBRXH7bZ8sJ0VYwvPwQpF45hv9dZZHRNzKIUmNTf6dUVv5EPFewtByGQoClZvKD/fXSIvge3qZfKxBshCZEs8CASEVRIHhz2IlJQ4sVaXrzt3g3rqH8vdL59zi92UKuFtmi9HlO4Q67TIC+TM5rdZj+FttSx7WAWZ2fpB++vJx4fUHsLt8KdhbHGw49q4QanVAZj/lzRmNixIR57iU9JmhBT/grkEwdIE8yCe1TP2XBrBAeo0FzKOjEwSoRxAGXSxgXRWZF/jj6qFhE0o97eaw/ozqrrjDlorOglg9GTY+Vhz8u5j0t209zSQ2wjVU8SfwU+6FjKvH5CT8vnF+Yss93J9ytthbnGzKWF4Fo0uZmo=
    file:
    - services/core/build/libs/core-exec.jar
    - services/email/build/libs/email-exec.jar
    - services/monitor/build/libs/monitor-exec.jar
    - services/rates/build/libs/rates-exec.jar
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^(release|beta)-.*$"
  - provider: script
    script: export ICONATOR_DOCKER_VERSION=$TRAVIS_TAG && sh docker/docker_push.sh
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^(release|beta)-.*$"
  - provider: script
    script: export ICONATOR_DOCKER_IMAGE_NAME=master && sh docker/docker_push.sh
    skip_cleanup: true
    on:
      branch: master
notifications:
  slack:
    secure: f33PFQnTCfuFT8sEd1SrDdSiXP7h6U8seVHw+oXOmsDF307uiY+ZEVlCPpA4ijxAirgda0zz/eVc3ez1zZmGScV3aiLXUog3VJHiBlddkooeCGXajYCRqoHLKI92oGbFhHWZxaEeDlNwOkGiWF1jplODrUP1OiFIRaUFpaKnJPfe1K4oM653qW30fFgi4JcLkkPffc6rPVOaiMugP7Hg1OOLeKal0SXnKxxiZbcS+hjfe2e5nLzl6Smu6gk73FeZl8tttC6XqpbMltv4/6pJrtdr6uakCSHWPtvYWLtEHmXrm1ucH1Ri0DHoZsws+R+nxVmc9QCNfOGP7wQr8D88E6C1Zx+J6x9T0cJL9dE7aNmxXkMScr6eFSLjla3FZZf/L6czl6VC+8slOup/Pd0i8wblvoZDkcpHNx989Iyej4oCZP521wrsWJk4U81zqaDnKvZMMgWaySm5EWl7DoGsapdH2ZimYrdZkXIB8i6/pRcNuq+7svqwUnkE4yPW88Q+hJ8xR5pZ9CRVPqSw2StqDOtKE4BHjI5tdhSfG6NDQh1vEW5RXGNxfDaNb1wPI6x6lXj5DQfqp0vXjVqh6o/lQQwX9pbXy/Q8hCN8Zm+VL+b0Tvj7DQF/mBu08JwqQ2gW+hOfUBAuGbsGlyZG4VWXy74tmGCcQ9m98b3Tzt+cz4U=
